name: SIDDIK_BOT
 
on:
  push:
    branches: [ main ]
 
concurrency:
  group: siddik-bot
  cancel-in-progress: true
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
 
      - name: Install dependencies
        run: npm install --legacy-peer-deps --no-audit --no-fund
 
      - name: Start SIDDIK_BOT
        run: npm start
